#!/bin/bash

pwfile="/data/files/pwd"
if [ -z "$1" ]; then
	echo " "
	echo "Inserisci il nome utente da creare "
	echo " "
	exit 1
fi
u=$(echo $1|tr -cd -- "[A-Za-z0-9.-]_.-")
row="$(grep -n $u $pwfile)"
if [ $? -ne 1 ]; then
	echo "l'utente $u esiste già"
	exit 2
fi
read -s -p "Inserisci la password per l'utente $u : " p
echo " "
if [ ${#p} -lt 8 ]; then
	echo " "
	echo " "
	echo "ERRORE"
	echo "la password deve essere lunga almeno 8 caratteri"
	echo " "
	exit 3
fi

phash="$(doveadm pw -s CRAM-MD5 -p $p)"

echo "$u:$phash::::" >> $pwfile

echo " "
echo " "

if [ $? -ne 0 ]; then
	echo "Errore nel creare l'utente"
else
	echo "Fatto"
fi
echo " "


