#!/bin/bash

pwfile="/data/files/pwd"
if [ -z "$1" ]; then
	echo " "
	echo "Inserisci il nome utente a cui cambiare la password "
	echo " "
	exit 1
fi
u=$(echo $1|tr -cd [A-Za-z0-9.-])
row="$(grep -n $u $pwfile)"
if [ $? -ne 0 ]; then
	echo "l'utente $u non esiste"
	exit 2
fi
read -s -p "Inserisci la nuova password per l'utente $u : " p
echo " "
if [ ${#p} -lt 8 ]; then
	echo " "
	echo " "
	echo "ERRORE"
	echo "la password deve essere lunga almeno 8 caratteri"
	echo " "
	exit 3
fi

phash="$(doveadm pw -s CRAM-MD5 -p $p)"

sed -i -r "s/^($u):([^:]*):([^:]*):/\1:$phash:\3/" $pwfile

echo " "
echo " "

if [ $? -ne 0 ]; then
	echo "Errore nel cambiare password"
else
	echo "Fatto"
fi
echo " "


